"""
3. Write a function nearly_equal to test whether two strings are nearly equal.
Two strings a and b are nearly equal when a can be generated by a single mutation on b.
>>> nearly_equal('python', 'perl') 
False 
>>> nearly_equal('perl', 'pearl') 
True
"""

def nearly_equal(string_1 : str, string_2 : str) -> bool:
    pass

if __name__ == "__main__":
    pass